# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from eufs_msgs/EKFErr.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class EKFErr(genpy.Message):
  _md5sum = "183f1bb90ac72a6c9c108dee51aba1c8"
  _type = "eufs_msgs/EKFErr"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """# Message for the error of the EKF. All of them are based on euclidean distances.
Header header

float64 gps_x_vel_err
float64 gps_y_vel_err
float64 imu_x_acc_err
float64 imu_y_acc_err
float64 imu_yaw_err
float64 ekf_x_vel_var
float64 ekf_y_vel_var
float64 ekf_x_acc_var
float64 ekf_y_acc_var
float64 ekf_yaw_var

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','gps_x_vel_err','gps_y_vel_err','imu_x_acc_err','imu_y_acc_err','imu_yaw_err','ekf_x_vel_var','ekf_y_vel_var','ekf_x_acc_var','ekf_y_acc_var','ekf_yaw_var']
  _slot_types = ['std_msgs/Header','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,gps_x_vel_err,gps_y_vel_err,imu_x_acc_err,imu_y_acc_err,imu_yaw_err,ekf_x_vel_var,ekf_y_vel_var,ekf_x_acc_var,ekf_y_acc_var,ekf_yaw_var

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(EKFErr, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.gps_x_vel_err is None:
        self.gps_x_vel_err = 0.
      if self.gps_y_vel_err is None:
        self.gps_y_vel_err = 0.
      if self.imu_x_acc_err is None:
        self.imu_x_acc_err = 0.
      if self.imu_y_acc_err is None:
        self.imu_y_acc_err = 0.
      if self.imu_yaw_err is None:
        self.imu_yaw_err = 0.
      if self.ekf_x_vel_var is None:
        self.ekf_x_vel_var = 0.
      if self.ekf_y_vel_var is None:
        self.ekf_y_vel_var = 0.
      if self.ekf_x_acc_var is None:
        self.ekf_x_acc_var = 0.
      if self.ekf_y_acc_var is None:
        self.ekf_y_acc_var = 0.
      if self.ekf_yaw_var is None:
        self.ekf_yaw_var = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.gps_x_vel_err = 0.
      self.gps_y_vel_err = 0.
      self.imu_x_acc_err = 0.
      self.imu_y_acc_err = 0.
      self.imu_yaw_err = 0.
      self.ekf_x_vel_var = 0.
      self.ekf_y_vel_var = 0.
      self.ekf_x_acc_var = 0.
      self.ekf_y_acc_var = 0.
      self.ekf_yaw_var = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_10d().pack(_x.gps_x_vel_err, _x.gps_y_vel_err, _x.imu_x_acc_err, _x.imu_y_acc_err, _x.imu_yaw_err, _x.ekf_x_vel_var, _x.ekf_y_vel_var, _x.ekf_x_acc_var, _x.ekf_y_acc_var, _x.ekf_yaw_var))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 80
      (_x.gps_x_vel_err, _x.gps_y_vel_err, _x.imu_x_acc_err, _x.imu_y_acc_err, _x.imu_yaw_err, _x.ekf_x_vel_var, _x.ekf_y_vel_var, _x.ekf_x_acc_var, _x.ekf_y_acc_var, _x.ekf_yaw_var,) = _get_struct_10d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_10d().pack(_x.gps_x_vel_err, _x.gps_y_vel_err, _x.imu_x_acc_err, _x.imu_y_acc_err, _x.imu_yaw_err, _x.ekf_x_vel_var, _x.ekf_y_vel_var, _x.ekf_x_acc_var, _x.ekf_y_acc_var, _x.ekf_yaw_var))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 80
      (_x.gps_x_vel_err, _x.gps_y_vel_err, _x.imu_x_acc_err, _x.imu_y_acc_err, _x.imu_yaw_err, _x.ekf_x_vel_var, _x.ekf_y_vel_var, _x.ekf_x_acc_var, _x.ekf_y_acc_var, _x.ekf_yaw_var,) = _get_struct_10d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_10d = None
def _get_struct_10d():
    global _struct_10d
    if _struct_10d is None:
        _struct_10d = struct.Struct("<10d")
    return _struct_10d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
