// Generated by gencpp from file eufs_msgs/WheelSpeeds.msg
// DO NOT EDIT!


#ifndef EUFS_MSGS_MESSAGE_WHEELSPEEDS_H
#define EUFS_MSGS_MESSAGE_WHEELSPEEDS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace eufs_msgs
{
template <class ContainerAllocator>
struct WheelSpeeds_
{
  typedef WheelSpeeds_<ContainerAllocator> Type;

  WheelSpeeds_()
    : steering(0.0)
    , lf_speed(0.0)
    , rf_speed(0.0)
    , lb_speed(0.0)
    , rb_speed(0.0)  {
    }
  WheelSpeeds_(const ContainerAllocator& _alloc)
    : steering(0.0)
    , lf_speed(0.0)
    , rf_speed(0.0)
    , lb_speed(0.0)
    , rb_speed(0.0)  {
  (void)_alloc;
    }



   typedef float _steering_type;
  _steering_type steering;

   typedef float _lf_speed_type;
  _lf_speed_type lf_speed;

   typedef float _rf_speed_type;
  _rf_speed_type rf_speed;

   typedef float _lb_speed_type;
  _lb_speed_type lb_speed;

   typedef float _rb_speed_type;
  _rb_speed_type rb_speed;





  typedef boost::shared_ptr< ::eufs_msgs::WheelSpeeds_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::eufs_msgs::WheelSpeeds_<ContainerAllocator> const> ConstPtr;

}; // struct WheelSpeeds_

typedef ::eufs_msgs::WheelSpeeds_<std::allocator<void> > WheelSpeeds;

typedef boost::shared_ptr< ::eufs_msgs::WheelSpeeds > WheelSpeedsPtr;
typedef boost::shared_ptr< ::eufs_msgs::WheelSpeeds const> WheelSpeedsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::eufs_msgs::WheelSpeeds_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::eufs_msgs::WheelSpeeds_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::eufs_msgs::WheelSpeeds_<ContainerAllocator1> & lhs, const ::eufs_msgs::WheelSpeeds_<ContainerAllocator2> & rhs)
{
  return lhs.steering == rhs.steering &&
    lhs.lf_speed == rhs.lf_speed &&
    lhs.rf_speed == rhs.rf_speed &&
    lhs.lb_speed == rhs.lb_speed &&
    lhs.rb_speed == rhs.rb_speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::eufs_msgs::WheelSpeeds_<ContainerAllocator1> & lhs, const ::eufs_msgs::WheelSpeeds_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace eufs_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::eufs_msgs::WheelSpeeds_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::eufs_msgs::WheelSpeeds_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::eufs_msgs::WheelSpeeds_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::eufs_msgs::WheelSpeeds_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::eufs_msgs::WheelSpeeds_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::eufs_msgs::WheelSpeeds_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::eufs_msgs::WheelSpeeds_<ContainerAllocator> >
{
  static const char* value()
  {
    return "032f31bfd4ad524fa752e1644fb5e2ab";
  }

  static const char* value(const ::eufs_msgs::WheelSpeeds_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x032f31bfd4ad524fULL;
  static const uint64_t static_value2 = 0xa752e1644fb5e2abULL;
};

template<class ContainerAllocator>
struct DataType< ::eufs_msgs::WheelSpeeds_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eufs_msgs/WheelSpeeds";
  }

  static const char* value(const ::eufs_msgs::WheelSpeeds_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::eufs_msgs::WheelSpeeds_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 steering\n"
"float32 lf_speed\n"
"float32 rf_speed\n"
"float32 lb_speed\n"
"float32 rb_speed\n"
"\n"
"# Steering is in radians\n"
"# Speeds are in RPM\n"
;
  }

  static const char* value(const ::eufs_msgs::WheelSpeeds_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::eufs_msgs::WheelSpeeds_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.steering);
      stream.next(m.lf_speed);
      stream.next(m.rf_speed);
      stream.next(m.lb_speed);
      stream.next(m.rb_speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WheelSpeeds_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::eufs_msgs::WheelSpeeds_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::eufs_msgs::WheelSpeeds_<ContainerAllocator>& v)
  {
    s << indent << "steering: ";
    Printer<float>::stream(s, indent + "  ", v.steering);
    s << indent << "lf_speed: ";
    Printer<float>::stream(s, indent + "  ", v.lf_speed);
    s << indent << "rf_speed: ";
    Printer<float>::stream(s, indent + "  ", v.rf_speed);
    s << indent << "lb_speed: ";
    Printer<float>::stream(s, indent + "  ", v.lb_speed);
    s << indent << "rb_speed: ";
    Printer<float>::stream(s, indent + "  ", v.rb_speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EUFS_MSGS_MESSAGE_WHEELSPEEDS_H
