# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from eufs_msgs/ConeArrayWithCovariance.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import eufs_msgs.msg
import geometry_msgs.msg
import std_msgs.msg

class ConeArrayWithCovariance(genpy.Message):
  _md5sum = "e5f10da6162fc97ab08945c47837cb2d"
  _type = "eufs_msgs/ConeArrayWithCovariance"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """#Array of 2D cone locations (z = 0) with covariances

Header header

ConeWithCovariance[] blue_cones
ConeWithCovariance[] yellow_cones
ConeWithCovariance[] orange_cones
ConeWithCovariance[] big_orange_cones
ConeWithCovariance[] unknown_color_cones

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: eufs_msgs/ConeWithCovariance
# Cone information

geometry_msgs/Point point
float64[4] covariance
================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['header','blue_cones','yellow_cones','orange_cones','big_orange_cones','unknown_color_cones']
  _slot_types = ['std_msgs/Header','eufs_msgs/ConeWithCovariance[]','eufs_msgs/ConeWithCovariance[]','eufs_msgs/ConeWithCovariance[]','eufs_msgs/ConeWithCovariance[]','eufs_msgs/ConeWithCovariance[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,blue_cones,yellow_cones,orange_cones,big_orange_cones,unknown_color_cones

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ConeArrayWithCovariance, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.blue_cones is None:
        self.blue_cones = []
      if self.yellow_cones is None:
        self.yellow_cones = []
      if self.orange_cones is None:
        self.orange_cones = []
      if self.big_orange_cones is None:
        self.big_orange_cones = []
      if self.unknown_color_cones is None:
        self.unknown_color_cones = []
    else:
      self.header = std_msgs.msg.Header()
      self.blue_cones = []
      self.yellow_cones = []
      self.orange_cones = []
      self.big_orange_cones = []
      self.unknown_color_cones = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.blue_cones)
      buff.write(_struct_I.pack(length))
      for val1 in self.blue_cones:
        _v1 = val1.point
        _x = _v1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        buff.write(_get_struct_4d().pack(*val1.covariance))
      length = len(self.yellow_cones)
      buff.write(_struct_I.pack(length))
      for val1 in self.yellow_cones:
        _v2 = val1.point
        _x = _v2
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        buff.write(_get_struct_4d().pack(*val1.covariance))
      length = len(self.orange_cones)
      buff.write(_struct_I.pack(length))
      for val1 in self.orange_cones:
        _v3 = val1.point
        _x = _v3
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        buff.write(_get_struct_4d().pack(*val1.covariance))
      length = len(self.big_orange_cones)
      buff.write(_struct_I.pack(length))
      for val1 in self.big_orange_cones:
        _v4 = val1.point
        _x = _v4
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        buff.write(_get_struct_4d().pack(*val1.covariance))
      length = len(self.unknown_color_cones)
      buff.write(_struct_I.pack(length))
      for val1 in self.unknown_color_cones:
        _v5 = val1.point
        _x = _v5
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        buff.write(_get_struct_4d().pack(*val1.covariance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.blue_cones is None:
        self.blue_cones = None
      if self.yellow_cones is None:
        self.yellow_cones = None
      if self.orange_cones is None:
        self.orange_cones = None
      if self.big_orange_cones is None:
        self.big_orange_cones = None
      if self.unknown_color_cones is None:
        self.unknown_color_cones = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.blue_cones = []
      for i in range(0, length):
        val1 = eufs_msgs.msg.ConeWithCovariance()
        _v6 = val1.point
        _x = _v6
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        start = end
        end += 32
        val1.covariance = _get_struct_4d().unpack(str[start:end])
        self.blue_cones.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.yellow_cones = []
      for i in range(0, length):
        val1 = eufs_msgs.msg.ConeWithCovariance()
        _v7 = val1.point
        _x = _v7
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        start = end
        end += 32
        val1.covariance = _get_struct_4d().unpack(str[start:end])
        self.yellow_cones.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.orange_cones = []
      for i in range(0, length):
        val1 = eufs_msgs.msg.ConeWithCovariance()
        _v8 = val1.point
        _x = _v8
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        start = end
        end += 32
        val1.covariance = _get_struct_4d().unpack(str[start:end])
        self.orange_cones.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.big_orange_cones = []
      for i in range(0, length):
        val1 = eufs_msgs.msg.ConeWithCovariance()
        _v9 = val1.point
        _x = _v9
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        start = end
        end += 32
        val1.covariance = _get_struct_4d().unpack(str[start:end])
        self.big_orange_cones.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.unknown_color_cones = []
      for i in range(0, length):
        val1 = eufs_msgs.msg.ConeWithCovariance()
        _v10 = val1.point
        _x = _v10
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        start = end
        end += 32
        val1.covariance = _get_struct_4d().unpack(str[start:end])
        self.unknown_color_cones.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.blue_cones)
      buff.write(_struct_I.pack(length))
      for val1 in self.blue_cones:
        _v11 = val1.point
        _x = _v11
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        buff.write(val1.covariance.tostring())
      length = len(self.yellow_cones)
      buff.write(_struct_I.pack(length))
      for val1 in self.yellow_cones:
        _v12 = val1.point
        _x = _v12
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        buff.write(val1.covariance.tostring())
      length = len(self.orange_cones)
      buff.write(_struct_I.pack(length))
      for val1 in self.orange_cones:
        _v13 = val1.point
        _x = _v13
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        buff.write(val1.covariance.tostring())
      length = len(self.big_orange_cones)
      buff.write(_struct_I.pack(length))
      for val1 in self.big_orange_cones:
        _v14 = val1.point
        _x = _v14
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        buff.write(val1.covariance.tostring())
      length = len(self.unknown_color_cones)
      buff.write(_struct_I.pack(length))
      for val1 in self.unknown_color_cones:
        _v15 = val1.point
        _x = _v15
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        buff.write(val1.covariance.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.blue_cones is None:
        self.blue_cones = None
      if self.yellow_cones is None:
        self.yellow_cones = None
      if self.orange_cones is None:
        self.orange_cones = None
      if self.big_orange_cones is None:
        self.big_orange_cones = None
      if self.unknown_color_cones is None:
        self.unknown_color_cones = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.blue_cones = []
      for i in range(0, length):
        val1 = eufs_msgs.msg.ConeWithCovariance()
        _v16 = val1.point
        _x = _v16
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        start = end
        end += 32
        val1.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=4)
        self.blue_cones.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.yellow_cones = []
      for i in range(0, length):
        val1 = eufs_msgs.msg.ConeWithCovariance()
        _v17 = val1.point
        _x = _v17
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        start = end
        end += 32
        val1.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=4)
        self.yellow_cones.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.orange_cones = []
      for i in range(0, length):
        val1 = eufs_msgs.msg.ConeWithCovariance()
        _v18 = val1.point
        _x = _v18
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        start = end
        end += 32
        val1.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=4)
        self.orange_cones.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.big_orange_cones = []
      for i in range(0, length):
        val1 = eufs_msgs.msg.ConeWithCovariance()
        _v19 = val1.point
        _x = _v19
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        start = end
        end += 32
        val1.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=4)
        self.big_orange_cones.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.unknown_color_cones = []
      for i in range(0, length):
        val1 = eufs_msgs.msg.ConeWithCovariance()
        _v20 = val1.point
        _x = _v20
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        start = end
        end += 32
        val1.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=4)
        self.unknown_color_cones.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
