// Generated by gencpp from file eufs_msgs/ChassisCommand.msg
// DO NOT EDIT!


#ifndef EUFS_MSGS_MESSAGE_CHASSISCOMMAND_H
#define EUFS_MSGS_MESSAGE_CHASSISCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace eufs_msgs
{
template <class ContainerAllocator>
struct ChassisCommand_
{
  typedef ChassisCommand_<ContainerAllocator> Type;

  ChassisCommand_()
    : header()
    , sender()
    , throttle(0.0)
    , steering(0.0)
    , front_brake(0.0)  {
    }
  ChassisCommand_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , sender(_alloc)
    , throttle(0.0)
    , steering(0.0)
    , front_brake(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _sender_type;
  _sender_type sender;

   typedef double _throttle_type;
  _throttle_type throttle;

   typedef double _steering_type;
  _steering_type steering;

   typedef double _front_brake_type;
  _front_brake_type front_brake;





  typedef boost::shared_ptr< ::eufs_msgs::ChassisCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::eufs_msgs::ChassisCommand_<ContainerAllocator> const> ConstPtr;

}; // struct ChassisCommand_

typedef ::eufs_msgs::ChassisCommand_<std::allocator<void> > ChassisCommand;

typedef boost::shared_ptr< ::eufs_msgs::ChassisCommand > ChassisCommandPtr;
typedef boost::shared_ptr< ::eufs_msgs::ChassisCommand const> ChassisCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::eufs_msgs::ChassisCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::eufs_msgs::ChassisCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::eufs_msgs::ChassisCommand_<ContainerAllocator1> & lhs, const ::eufs_msgs::ChassisCommand_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.sender == rhs.sender &&
    lhs.throttle == rhs.throttle &&
    lhs.steering == rhs.steering &&
    lhs.front_brake == rhs.front_brake;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::eufs_msgs::ChassisCommand_<ContainerAllocator1> & lhs, const ::eufs_msgs::ChassisCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace eufs_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::eufs_msgs::ChassisCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::eufs_msgs::ChassisCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::eufs_msgs::ChassisCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::eufs_msgs::ChassisCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::eufs_msgs::ChassisCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::eufs_msgs::ChassisCommand_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::eufs_msgs::ChassisCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "003e7b9af89a02607c6acd00a5b81f03";
  }

  static const char* value(const ::eufs_msgs::ChassisCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x003e7b9af89a0260ULL;
  static const uint64_t static_value2 = 0x7c6acd00a5b81f03ULL;
};

template<class ContainerAllocator>
struct DataType< ::eufs_msgs::ChassisCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eufs_msgs/ChassisCommand";
  }

  static const char* value(const ::eufs_msgs::ChassisCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::eufs_msgs::ChassisCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"string sender\n"
"float64 throttle\n"
"float64 steering\n"
"float64 front_brake\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::eufs_msgs::ChassisCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::eufs_msgs::ChassisCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.sender);
      stream.next(m.throttle);
      stream.next(m.steering);
      stream.next(m.front_brake);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChassisCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::eufs_msgs::ChassisCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::eufs_msgs::ChassisCommand_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "sender: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.sender);
    s << indent << "throttle: ";
    Printer<double>::stream(s, indent + "  ", v.throttle);
    s << indent << "steering: ";
    Printer<double>::stream(s, indent + "  ", v.steering);
    s << indent << "front_brake: ";
    Printer<double>::stream(s, indent + "  ", v.front_brake);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EUFS_MSGS_MESSAGE_CHASSISCOMMAND_H
