// Generated by gencpp from file eufs_msgs/PathIntegralTiming.msg
// DO NOT EDIT!


#ifndef EUFS_MSGS_MESSAGE_PATHINTEGRALTIMING_H
#define EUFS_MSGS_MESSAGE_PATHINTEGRALTIMING_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace eufs_msgs
{
template <class ContainerAllocator>
struct PathIntegralTiming_
{
  typedef PathIntegralTiming_<ContainerAllocator> Type;

  PathIntegralTiming_()
    : header()
    , average_time_between_poses(0.0)
    , average_optimization_cycle_time(0.0)
    , average_sleep_time(0.0)  {
    }
  PathIntegralTiming_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , average_time_between_poses(0.0)
    , average_optimization_cycle_time(0.0)
    , average_sleep_time(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _average_time_between_poses_type;
  _average_time_between_poses_type average_time_between_poses;

   typedef double _average_optimization_cycle_time_type;
  _average_optimization_cycle_time_type average_optimization_cycle_time;

   typedef double _average_sleep_time_type;
  _average_sleep_time_type average_sleep_time;





  typedef boost::shared_ptr< ::eufs_msgs::PathIntegralTiming_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::eufs_msgs::PathIntegralTiming_<ContainerAllocator> const> ConstPtr;

}; // struct PathIntegralTiming_

typedef ::eufs_msgs::PathIntegralTiming_<std::allocator<void> > PathIntegralTiming;

typedef boost::shared_ptr< ::eufs_msgs::PathIntegralTiming > PathIntegralTimingPtr;
typedef boost::shared_ptr< ::eufs_msgs::PathIntegralTiming const> PathIntegralTimingConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::eufs_msgs::PathIntegralTiming_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::eufs_msgs::PathIntegralTiming_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::eufs_msgs::PathIntegralTiming_<ContainerAllocator1> & lhs, const ::eufs_msgs::PathIntegralTiming_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.average_time_between_poses == rhs.average_time_between_poses &&
    lhs.average_optimization_cycle_time == rhs.average_optimization_cycle_time &&
    lhs.average_sleep_time == rhs.average_sleep_time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::eufs_msgs::PathIntegralTiming_<ContainerAllocator1> & lhs, const ::eufs_msgs::PathIntegralTiming_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace eufs_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::eufs_msgs::PathIntegralTiming_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::eufs_msgs::PathIntegralTiming_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::eufs_msgs::PathIntegralTiming_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::eufs_msgs::PathIntegralTiming_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::eufs_msgs::PathIntegralTiming_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::eufs_msgs::PathIntegralTiming_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::eufs_msgs::PathIntegralTiming_<ContainerAllocator> >
{
  static const char* value()
  {
    return "da8d85f1b7925638bce827c1d42eeb1b";
  }

  static const char* value(const ::eufs_msgs::PathIntegralTiming_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xda8d85f1b7925638ULL;
  static const uint64_t static_value2 = 0xbce827c1d42eeb1bULL;
};

template<class ContainerAllocator>
struct DataType< ::eufs_msgs::PathIntegralTiming_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eufs_msgs/PathIntegralTiming";
  }

  static const char* value(const ::eufs_msgs::PathIntegralTiming_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::eufs_msgs::PathIntegralTiming_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"float64 average_time_between_poses\n"
"float64 average_optimization_cycle_time\n"
"float64 average_sleep_time\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::eufs_msgs::PathIntegralTiming_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::eufs_msgs::PathIntegralTiming_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.average_time_between_poses);
      stream.next(m.average_optimization_cycle_time);
      stream.next(m.average_sleep_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PathIntegralTiming_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::eufs_msgs::PathIntegralTiming_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::eufs_msgs::PathIntegralTiming_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "average_time_between_poses: ";
    Printer<double>::stream(s, indent + "  ", v.average_time_between_poses);
    s << indent << "average_optimization_cycle_time: ";
    Printer<double>::stream(s, indent + "  ", v.average_optimization_cycle_time);
    s << indent << "average_sleep_time: ";
    Printer<double>::stream(s, indent + "  ", v.average_sleep_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EUFS_MSGS_MESSAGE_PATHINTEGRALTIMING_H
