// Generated by gencpp from file eufs_msgs/SystemStatus.msg
// DO NOT EDIT!


#ifndef EUFS_MSGS_MESSAGE_SYSTEMSTATUS_H
#define EUFS_MSGS_MESSAGE_SYSTEMSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <eufs_msgs/TopicStatus.h>

namespace eufs_msgs
{
template <class ContainerAllocator>
struct SystemStatus_
{
  typedef SystemStatus_<ContainerAllocator> Type;

  SystemStatus_()
    : header()
    , topic_statuses()  {
    }
  SystemStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , topic_statuses(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::eufs_msgs::TopicStatus_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::eufs_msgs::TopicStatus_<ContainerAllocator> >::other >  _topic_statuses_type;
  _topic_statuses_type topic_statuses;





  typedef boost::shared_ptr< ::eufs_msgs::SystemStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::eufs_msgs::SystemStatus_<ContainerAllocator> const> ConstPtr;

}; // struct SystemStatus_

typedef ::eufs_msgs::SystemStatus_<std::allocator<void> > SystemStatus;

typedef boost::shared_ptr< ::eufs_msgs::SystemStatus > SystemStatusPtr;
typedef boost::shared_ptr< ::eufs_msgs::SystemStatus const> SystemStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::eufs_msgs::SystemStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::eufs_msgs::SystemStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::eufs_msgs::SystemStatus_<ContainerAllocator1> & lhs, const ::eufs_msgs::SystemStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.topic_statuses == rhs.topic_statuses;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::eufs_msgs::SystemStatus_<ContainerAllocator1> & lhs, const ::eufs_msgs::SystemStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace eufs_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::eufs_msgs::SystemStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::eufs_msgs::SystemStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::eufs_msgs::SystemStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::eufs_msgs::SystemStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::eufs_msgs::SystemStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::eufs_msgs::SystemStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::eufs_msgs::SystemStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5a06902117b2ce130952f57a9e31ee19";
  }

  static const char* value(const ::eufs_msgs::SystemStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5a06902117b2ce13ULL;
  static const uint64_t static_value2 = 0x0952f57a9e31ee19ULL;
};

template<class ContainerAllocator>
struct DataType< ::eufs_msgs::SystemStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eufs_msgs/SystemStatus";
  }

  static const char* value(const ::eufs_msgs::SystemStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::eufs_msgs::SystemStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"TopicStatus[] topic_statuses\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: eufs_msgs/TopicStatus\n"
"# Topic information\n"
"string topic\n"
"string description\n"
"string group\n"
"bool trigger_ebs\n"
"string log_level\n"
"\n"
"# Topic status\n"
"uint16 status\n"
"\n"
"uint16 OFF = 0\n"
"uint16 PUBLISHING = 1\n"
"uint16 TIMEOUT_EXCEEDED = 2\n"
;
  }

  static const char* value(const ::eufs_msgs::SystemStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::eufs_msgs::SystemStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.topic_statuses);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SystemStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::eufs_msgs::SystemStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::eufs_msgs::SystemStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "topic_statuses[]" << std::endl;
    for (size_t i = 0; i < v.topic_statuses.size(); ++i)
    {
      s << indent << "  topic_statuses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::eufs_msgs::TopicStatus_<ContainerAllocator> >::stream(s, indent + "    ", v.topic_statuses[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // EUFS_MSGS_MESSAGE_SYSTEMSTATUS_H
