(cl:in-package eufs_msgs-msg)
(cl:export '(GPS_RECEIVED-VAL
          GPS_RECEIVED
          IMU_RECEIVED-VAL
          IMU_RECEIVED
          WHEEL_ODOM_RECEIVED-VAL
          WHEEL_ODOM_RECEIVED
          EKF_ODOM_RECEIVED-VAL
          EKF_ODOM_RECEIVED
          EKF_ACCEL_RECEIVED-VAL
          EKF_ACCEL_RECEIVED
          CURRENTLY_OVER_COVARIANCE_LIMIT-VAL
          CURRENTLY_OVER_COVARIANCE_LIMIT
          CONSECUTIVE_TURNS_OVER_COVARIANCE_LIMIT-VAL
          CONSECUTIVE_TURNS_OVER_COVARIANCE_LIMIT
          RECOMMENDS_FAILURE-VAL
          RECOMMENDS_FAILURE
))