// Generated by gencpp from file eufs_msgs/CheckForObjectsResult.msg
// DO NOT EDIT!


#ifndef EUFS_MSGS_MESSAGE_CHECKFOROBJECTSRESULT_H
#define EUFS_MSGS_MESSAGE_CHECKFOROBJECTSRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <eufs_msgs/BoundingBoxes.h>

namespace eufs_msgs
{
template <class ContainerAllocator>
struct CheckForObjectsResult_
{
  typedef CheckForObjectsResult_<ContainerAllocator> Type;

  CheckForObjectsResult_()
    : id(0)
    , bounding_boxes()  {
    }
  CheckForObjectsResult_(const ContainerAllocator& _alloc)
    : id(0)
    , bounding_boxes(_alloc)  {
  (void)_alloc;
    }



   typedef int16_t _id_type;
  _id_type id;

   typedef  ::eufs_msgs::BoundingBoxes_<ContainerAllocator>  _bounding_boxes_type;
  _bounding_boxes_type bounding_boxes;





  typedef boost::shared_ptr< ::eufs_msgs::CheckForObjectsResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::eufs_msgs::CheckForObjectsResult_<ContainerAllocator> const> ConstPtr;

}; // struct CheckForObjectsResult_

typedef ::eufs_msgs::CheckForObjectsResult_<std::allocator<void> > CheckForObjectsResult;

typedef boost::shared_ptr< ::eufs_msgs::CheckForObjectsResult > CheckForObjectsResultPtr;
typedef boost::shared_ptr< ::eufs_msgs::CheckForObjectsResult const> CheckForObjectsResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::eufs_msgs::CheckForObjectsResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::eufs_msgs::CheckForObjectsResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::eufs_msgs::CheckForObjectsResult_<ContainerAllocator1> & lhs, const ::eufs_msgs::CheckForObjectsResult_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.bounding_boxes == rhs.bounding_boxes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::eufs_msgs::CheckForObjectsResult_<ContainerAllocator1> & lhs, const ::eufs_msgs::CheckForObjectsResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace eufs_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::eufs_msgs::CheckForObjectsResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::eufs_msgs::CheckForObjectsResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::eufs_msgs::CheckForObjectsResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::eufs_msgs::CheckForObjectsResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::eufs_msgs::CheckForObjectsResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::eufs_msgs::CheckForObjectsResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::eufs_msgs::CheckForObjectsResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e1c1eea05bd032baf074f5342bdbaf2c";
  }

  static const char* value(const ::eufs_msgs::CheckForObjectsResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe1c1eea05bd032baULL;
  static const uint64_t static_value2 = 0xf074f5342bdbaf2cULL;
};

template<class ContainerAllocator>
struct DataType< ::eufs_msgs::CheckForObjectsResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eufs_msgs/CheckForObjectsResult";
  }

  static const char* value(const ::eufs_msgs::CheckForObjectsResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::eufs_msgs::CheckForObjectsResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Result definition\n"
"int16 id\n"
"eufs_msgs/BoundingBoxes bounding_boxes\n"
"\n"
"\n"
"================================================================================\n"
"MSG: eufs_msgs/BoundingBoxes\n"
"Header header\n"
"Header image_header\n"
"BoundingBox[] bounding_boxes\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: eufs_msgs/BoundingBox\n"
"string Class\n"
"float64 probability\n"
"int64 xmin\n"
"int64 ymin\n"
"int64 xmax\n"
"int64 ymax\n"
;
  }

  static const char* value(const ::eufs_msgs::CheckForObjectsResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::eufs_msgs::CheckForObjectsResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.bounding_boxes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CheckForObjectsResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::eufs_msgs::CheckForObjectsResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::eufs_msgs::CheckForObjectsResult_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int16_t>::stream(s, indent + "  ", v.id);
    s << indent << "bounding_boxes: ";
    s << std::endl;
    Printer< ::eufs_msgs::BoundingBoxes_<ContainerAllocator> >::stream(s, indent + "  ", v.bounding_boxes);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EUFS_MSGS_MESSAGE_CHECKFOROBJECTSRESULT_H
