// Generated by gencpp from file eufs_msgs/PathIntegralStatus.msg
// DO NOT EDIT!


#ifndef EUFS_MSGS_MESSAGE_PATHINTEGRALSTATUS_H
#define EUFS_MSGS_MESSAGE_PATHINTEGRALSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace eufs_msgs
{
template <class ContainerAllocator>
struct PathIntegralStatus_
{
  typedef PathIntegralStatus_<ContainerAllocator> Type;

  PathIntegralStatus_()
    : header()
    , info()
    , status(0)  {
    }
  PathIntegralStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , info(_alloc)
    , status(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _info_type;
  _info_type info;

   typedef int32_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::eufs_msgs::PathIntegralStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::eufs_msgs::PathIntegralStatus_<ContainerAllocator> const> ConstPtr;

}; // struct PathIntegralStatus_

typedef ::eufs_msgs::PathIntegralStatus_<std::allocator<void> > PathIntegralStatus;

typedef boost::shared_ptr< ::eufs_msgs::PathIntegralStatus > PathIntegralStatusPtr;
typedef boost::shared_ptr< ::eufs_msgs::PathIntegralStatus const> PathIntegralStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::eufs_msgs::PathIntegralStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::eufs_msgs::PathIntegralStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::eufs_msgs::PathIntegralStatus_<ContainerAllocator1> & lhs, const ::eufs_msgs::PathIntegralStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.info == rhs.info &&
    lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::eufs_msgs::PathIntegralStatus_<ContainerAllocator1> & lhs, const ::eufs_msgs::PathIntegralStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace eufs_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::eufs_msgs::PathIntegralStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::eufs_msgs::PathIntegralStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::eufs_msgs::PathIntegralStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::eufs_msgs::PathIntegralStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::eufs_msgs::PathIntegralStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::eufs_msgs::PathIntegralStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::eufs_msgs::PathIntegralStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "02d521c9eb95ab130c6fffe5772d2229";
  }

  static const char* value(const ::eufs_msgs::PathIntegralStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x02d521c9eb95ab13ULL;
  static const uint64_t static_value2 = 0x0c6fffe5772d2229ULL;
};

template<class ContainerAllocator>
struct DataType< ::eufs_msgs::PathIntegralStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eufs_msgs/PathIntegralStatus";
  }

  static const char* value(const ::eufs_msgs::PathIntegralStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::eufs_msgs::PathIntegralStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"string info\n"
"int32 status\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::eufs_msgs::PathIntegralStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::eufs_msgs::PathIntegralStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.info);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PathIntegralStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::eufs_msgs::PathIntegralStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::eufs_msgs::PathIntegralStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "info: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.info);
    s << indent << "status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EUFS_MSGS_MESSAGE_PATHINTEGRALSTATUS_H
