// Generated by gencpp from file eufs_msgs/WheelSpeedsStamped.msg
// DO NOT EDIT!


#ifndef EUFS_MSGS_MESSAGE_WHEELSPEEDSSTAMPED_H
#define EUFS_MSGS_MESSAGE_WHEELSPEEDSSTAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace eufs_msgs
{
template <class ContainerAllocator>
struct WheelSpeedsStamped_
{
  typedef WheelSpeedsStamped_<ContainerAllocator> Type;

  WheelSpeedsStamped_()
    : header()
    , steering(0.0)
    , lf_speed(0.0)
    , rf_speed(0.0)
    , lb_speed(0.0)
    , rb_speed(0.0)  {
    }
  WheelSpeedsStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , steering(0.0)
    , lf_speed(0.0)
    , rf_speed(0.0)
    , lb_speed(0.0)
    , rb_speed(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _steering_type;
  _steering_type steering;

   typedef float _lf_speed_type;
  _lf_speed_type lf_speed;

   typedef float _rf_speed_type;
  _rf_speed_type rf_speed;

   typedef float _lb_speed_type;
  _lb_speed_type lb_speed;

   typedef float _rb_speed_type;
  _rb_speed_type rb_speed;





  typedef boost::shared_ptr< ::eufs_msgs::WheelSpeedsStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::eufs_msgs::WheelSpeedsStamped_<ContainerAllocator> const> ConstPtr;

}; // struct WheelSpeedsStamped_

typedef ::eufs_msgs::WheelSpeedsStamped_<std::allocator<void> > WheelSpeedsStamped;

typedef boost::shared_ptr< ::eufs_msgs::WheelSpeedsStamped > WheelSpeedsStampedPtr;
typedef boost::shared_ptr< ::eufs_msgs::WheelSpeedsStamped const> WheelSpeedsStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::eufs_msgs::WheelSpeedsStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::eufs_msgs::WheelSpeedsStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::eufs_msgs::WheelSpeedsStamped_<ContainerAllocator1> & lhs, const ::eufs_msgs::WheelSpeedsStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.steering == rhs.steering &&
    lhs.lf_speed == rhs.lf_speed &&
    lhs.rf_speed == rhs.rf_speed &&
    lhs.lb_speed == rhs.lb_speed &&
    lhs.rb_speed == rhs.rb_speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::eufs_msgs::WheelSpeedsStamped_<ContainerAllocator1> & lhs, const ::eufs_msgs::WheelSpeedsStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace eufs_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::eufs_msgs::WheelSpeedsStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::eufs_msgs::WheelSpeedsStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::eufs_msgs::WheelSpeedsStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::eufs_msgs::WheelSpeedsStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::eufs_msgs::WheelSpeedsStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::eufs_msgs::WheelSpeedsStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::eufs_msgs::WheelSpeedsStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "478e5adefb6b1f69dba1fd1279c68795";
  }

  static const char* value(const ::eufs_msgs::WheelSpeedsStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x478e5adefb6b1f69ULL;
  static const uint64_t static_value2 = 0xdba1fd1279c68795ULL;
};

template<class ContainerAllocator>
struct DataType< ::eufs_msgs::WheelSpeedsStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eufs_msgs/WheelSpeedsStamped";
  }

  static const char* value(const ::eufs_msgs::WheelSpeedsStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::eufs_msgs::WheelSpeedsStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"float32 steering\n"
"float32 lf_speed\n"
"float32 rf_speed\n"
"float32 lb_speed\n"
"float32 rb_speed\n"
"\n"
"# Steering is in radians\n"
"# Speeds are in RPM\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::eufs_msgs::WheelSpeedsStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::eufs_msgs::WheelSpeedsStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.steering);
      stream.next(m.lf_speed);
      stream.next(m.rf_speed);
      stream.next(m.lb_speed);
      stream.next(m.rb_speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WheelSpeedsStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::eufs_msgs::WheelSpeedsStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::eufs_msgs::WheelSpeedsStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "steering: ";
    Printer<float>::stream(s, indent + "  ", v.steering);
    s << indent << "lf_speed: ";
    Printer<float>::stream(s, indent + "  ", v.lf_speed);
    s << indent << "rf_speed: ";
    Printer<float>::stream(s, indent + "  ", v.rf_speed);
    s << indent << "lb_speed: ";
    Printer<float>::stream(s, indent + "  ", v.lb_speed);
    s << indent << "rb_speed: ";
    Printer<float>::stream(s, indent + "  ", v.rb_speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EUFS_MSGS_MESSAGE_WHEELSPEEDSSTAMPED_H
